services:
  jekyll:
    image: "jekyll/jekyll:latest"
    command: jekyll serve --watch --incremental
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 4000:4000
    volumes:
      - /home/koala/Projects/brandon-feder.github.io:/srv/jekyll